swagger: '2.0'
info:
  title: FIU Callback API
  x-custom-tags:
    x-changelog: >-
      <p> 1. Updated /FI/Notification to support Partial Fetch Usecase<br> 2.
      New Enums Added for FIStatus - READY / DENIED / PENDING / DELIVERED /
      TIMEOUT<br> </p>
    x-api-name: Financial Information User (FIU) Callback API
  description: >-
    # Summary

    This is a callback interface hosted by the AA Client or FIU to receive
    asynchronous status update notification on the aggregation request. 
    

    ---
  version: 1.1.2
  contact:
    email: aa-api@rebit.org.in
tags:
  - name: Notifications
    description: >-
      Notifies to the AA client or FIU about the data-flow events and
      consent-flow events
securityDefinitions:
  AA_api_key:
    type: apiKey
    name: aa_api_key
    in: header
security:
  - AA_api_key: []
consumes:
  - application/json
produces:
  - application/json
paths:
  /Consent/Notification:
    post:
      tags:
        - Notifications
      description: >-
        API handles the notifications corresponding to the events generated
        during consent flow.

        <br>Note: "Request Body Example Value" and "Responses Example Value"
        given below is for illustrative purposes only.
      parameters:
        - name: x-jws-signature
          type: string
          format: byte
          in: header
          required: true
          description: Detached JWS of the body
        - name: body
          required: true
          in: body
          schema:
            $ref: '#/definitions/ConsentStatusNotification'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/NotificationResponse'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
        '400':
          description: Bad Request
          schema:
              $ref: '#/definitions/BadRequestConsentNotification'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
        '401':
          description: Unauthorized Access
          schema:
              $ref: '#/definitions/UnauthorizedAccess'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body                

        '404':
          description: Not Found
          schema:
              $ref: '#/definitions/NotFound'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
        '409':
          description: Conflict
          schema:
              $ref: '#/definitions/Conflict'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
        '412':
          description: Precondition failed
          schema:
              $ref: '#/definitions/PreconditionFailed'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/InternalServerError'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
        '501':
          description: Not Implemented
          schema:
              $ref: '#/definitions/NotImplemented'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
        '503':
          description: Service Unavailable
          schema:
              $ref: '#/definitions/ServiceUnavailable'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
  /FI/Notification:
    post:
      tags:
        - Notifications
      description: >-
        API handles the notifications corresponding to the events generated
        during data-flow.

        <br>Note: "Request Body Example Value" and "Responses Example Value"
        given below is for illustrative purposes only.
      parameters:
        - name: x-jws-signature
          type: string
          format: byte
          in: header
          required: true
          description: Detached JWS of the body
        - name: body
          required: true
          in: body
          schema:
            $ref: '#/definitions/FIStatusNotification'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/NotificationResponse'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
        '400':
          description: Bad Request
          schema:
              $ref: '#/definitions/BadRequestFINotification'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
                
        '401':
          description: Unauthorized Access
          schema:
              $ref: '#/definitions/UnauthorizedAccess'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
        '404':
          description: Not Found
          schema:
              $ref: '#/definitions/NotFound'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
        '409':
          description: Conflict
          schema:
              $ref: '#/definitions/Conflict'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
        '412':
          description: Precondition failed
          schema:
              $ref: '#/definitions/PreconditionFailed'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
        '500':
          description: Internal Server Error
          schema:
              $ref: '#/definitions/InternalServerError'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
        '501':
          description: Not Implemented
          schema:
              $ref: '#/definitions/NotImplemented'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
        '503':
          description: Service Unavailable
          schema:
              $ref: '#/definitions/ServiceUnavailable'
          headers:
            x-jws-signature:
                type: string
                format: byte
                description: Detached JWS of the response body
schemes:
  - https
definitions:
  ConsentStatusNotification:
    description: ''
    type: object
    required:
      - ver
      - timestamp
      - txnid
      - Notifier
      - ConsentStatusNotification
    properties:
      ver:
        type: string
        example: '1.0'
        description: The version of the API
        xml:
          attribute: true
      timestamp:
        type: string
        format: date-time
        example: '2018-12-06T11:39:57.153Z'
        description: Creation timestamp of the message which will be updated at each leg
        xml:
          attribute: true
      txnid:
        type: string
        description: >-
          The unique transaction identifier used for providing an end to end
          traceability. 
        example: 0b811819-9044-4856-b0ee-8c88035f8858
        xml:
          attribute: true
      Notifier:
        type: object
        description: Information about the notifier
        properties:
          type:
            type: string
            description: ''
            example: AA
            xml:
              attribute: true
          id:
            type: string
            description: >-
              Value of the destination address for locating the resource to
              maintain the logs
            example: AA-1
            xml:
              attribute: true
      ConsentStatusNotification:
        type: object
        description: >-
          Selects a type of  Data-flow events , Consent-flow events, and Account
          discovery flow events. When this notification is received for a newly
          created consent with ACTIVE consentStatus, then consentHandle must also be provided.
          This is so that FIU can map the consentHandle with consentStatus.
        properties:
          consentId:
            type: string
            example: XXXX0-XXXX-XXXX
            xml:
              attribute: true
          consentHandle:
            type: string
            example: XXXX0-XXXX-XXXX
            xml:
              attribute: true
          consentStatus:
            type: string
            enum:
              - ACTIVE
              - PENDING
              - REVOKED
              - PAUSED
              - REJECTED
              - EXPIRED
            example: PAUSED
            xml:
              attribute: true
        xml:
          name: ConsentStatusNotification
  FIStatusNotification:
    description: ''
    type: object
    required:
      - ver
      - timestamp
      - txnid
      - Notifier
      - FIStatusNotification
    properties:
      ver:
        type: string
        example: '1.0'
        description: The version of the API
        xml:
          attribute: true
      timestamp:
        type: string
        format: date-time
        example: '2018-12-06T11:39:57.153Z'
        description: Creation timestamp of the message which will be updated at each leg
        xml:
          attribute: true
      txnid:
        type: string
        description: >-
          The unique transaction identifier used for providing an end to end
          traceability. 
        example: 0b811819-9044-4856-b0ee-8c88035f8858
        xml:
          attribute: true
      Notifier:
        type: object
        description: Information about the notifier
        properties:
          type:
            type: string
            description: ''
            example: AA
            xml:
              attribute: true
          id:
            type: string
            description: >-
              Value of the destination address for locating the resource to
              maintain the logs
            example: AA-1
            xml:
              attribute: true
      FIStatusNotification:
        type: object
        description: >-
          Selects a type of  Data-flow events , Consent-flow events, and Account
          discovery flow events
        required:
          - sessionId
          - sessionStatus
          - FIStatusResponse
        properties:
          sessionId:
            type: string
            example: XXXX0-XXXX-XXXX
            xml:
              attribute: true
          sessionStatus:
            type: string
            example: ACTIVE
            enum:
              - ACTIVE
              - COMPLETED
              - EXPIRED
              - FAILED
          FIStatusResponse:
            type: array
            items:
              type: object
              required:
                - fipID
                - Accounts
              properties:
                fipID:
                  type: string
                  example: FIP-1
                Accounts:
                  type: array
                  items:
                    type: object
                    required:
                      - linkRefNumber
                      - FIStatus
                      - description
                    properties:
                      linkRefNumber:
                        type: string
                        example: XXXX-XXXX-XXXX
                      FIStatus:
                        type: string
                        enum:
                          - READY
                          - DENIED
                          - PENDING
                          - DELIVERED
                          - TIMEOUT
                        example: READY
                        xml:
                          attribute: true
                      description:
                        type: string
                        example: ''
  ErrorResponse:
    description: Generic Error Response. Specific Error Responses extend from this.
    type: object
    required:
      - ver
      - txnid
      - timestamp
      - errorCode
      - errorMsg
    properties:
      ver:
        type: string
        description: The version of the API
        example: '1.0'
        xml:
          attribute: true
      timestamp:
        type: string
        description: Creation timestamp of the message which will be updated at each call
        format: date-time
        example: '2018-09-22T06:13:30.967+0000'
        xml:
          attribute: true
      txnid:
        type: string
        description: >-
          An unique transaction identifier used for providing an end to end
          traceability.
        example: f35761ac-4a18-11e8-96ff-0277a9fbfed
      errorCode:
        type: string
        description: Error code pertaining to the invalid request
        xml:
          attribute: true
      errorMsg:
        type: string
        example: "Error code specific error message"
  BadRequest:
    description: Response to bad request.
    allOf:
      - $ref: '#/definitions/ErrorResponse'
    properties:
      errorCode:
        type: string
        description: Error code pertaining to the invalid request
        enum:
          - InvalidRequest
          - InvalidURI
          - InvalidSecurity
          - SignatureDoesNotMatch
        xml:
          attribute: true
  NotFound:
    description: Requested resource was not found.
    allOf:
      - $ref: '#/definitions/ErrorResponse'
    properties:
      errorCode:
        type: string
        description: Indicates that the version ID specified in the request does not match an existing version
        enum:
          - NoSuchVersion
        xml:
          attribute: true
  Conflict:
    description: IdempotencyError When UUID/Id is not unique
    allOf:
      - $ref: '#/definitions/ErrorResponse'
    properties:
      errorCode:
        description: IdempotencyError When UUID/Id is not unique
        type: string
        enum:
          - IdempotencyError
        xml:
          attribute: true
  PreconditionFailed:
    description: At least one of the preconditions you specified did not hold
    allOf:
      - $ref: '#/definitions/ErrorResponse'
    properties:
      errorCode:
        type: string
        enum:
          - PreconditionFailed
        xml:
          attribute: true
  InternalServerError:
    description: Encountered an internal error. Please try again
    allOf:
      - $ref: '#/definitions/ErrorResponse'
    properties:
      errorCode:
        type: string
        enum:
          - InternalError
        xml:
          attribute: true
  NotImplemented:
    description: Trying to access an unimplemented feature/API. Required when we provide backward compatiable API.
    allOf:
      - $ref: '#/definitions/ErrorResponse'
    properties:
      errorCode:
        type: string
        enum:
          - NotImplemented
        xml:
          attribute: true
  ServiceUnavailable:
    description: Service is unavailable
    allOf:
      - $ref: '#/definitions/ErrorResponse'
    properties:
      errorCode:
        type: string
        enum:
          - ServiceUnavailable
        xml:
          attribute: true
          
  UnauthorizedAccess:
    description: Unauthorized Access
    allOf:
      - $ref: '#/definitions/ErrorResponse'
    properties:
      errorCode:
        type: string
        enum:
          - Unauthorized
        xml:
          attribute: true
          
  NotificationResponse:
    description: Success response for receiving notification
    required:
      - ver
      - timestamp
      - txnid
      - response
    properties:
      ver:
        type: string
        description: The version of the API
        example: '1.0'
        xml:
          attribute: true
      timestamp:
        type: string
        description: Creation timestamp of the message which will be updated at each call
        format: date-time
        example: '2018-09-22T06:13:30.967+0000'
        xml:
          attribute: true
      txnid:
        type: string
        description: >-
          An unique transaction identifier used for providing an end to end
          traceability.
        example: f35761ac-4a18-11e8-96ff-0277a9fbfedc
        xml:
          attribute: true
      response:
        type: string
        description: response description
        example: OK
    xml:
      name: ConsentNotificationResponse
      namespace: 'https://standards.rebit.org.in/aa'
  BadRequestConsentNotification:
    description: Bad Request during Consent Notification
    allOf:
      - $ref: '#/definitions/BadRequest'
    properties:
      errorCode:
        type: string
        enum:
          - InvalidRequest
          - InvalidURI
          - InvalidSecurity
          - SignatureDoesNotMatch
          - InvalidNotifier
          - InvalidConsentId
          - InvalidConsentStatus
        xml:
          attribute: true
  BadRequestFINotification:
    description: Bad Request during Consent Notification
    allOf:
      - $ref: '#/definitions/BadRequest'
    properties:
      errorCode:
        type: string
        enum:
          - InvalidRequest
          - InvalidURI
          - InvalidSecurity
          - SignatureDoesNotMatch
          - InvalidSessionId
          - InvalidSessionStatus
          - InvalidFIStatus
        xml:
          attribute: true
