name: government_securities

on: 
  push:
    branches: [ main ]
    paths:
      - 'schemas/government_securities/**'
      - utils/gh-actions/schemas-action-generator.sh
  pull_request:
    paths:
      - 'schemas/government_securities/**'
      - utils/gh-actions/schemas-action-generator.sh

jobs:
  lint-government_securities:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: korelstar/xmllint-problem-matcher@v1
    - name: Lint Schema & XML
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./schemas/government_securities/Govt_securities.xml
        xml-schema-file: ./schemas/government_securities/govt_securities.xsd
