name: alternative_investment_funds

on: 
  push:
    branches: [ main ]
    paths:
      - 'schemas/alternative_investment_funds/**'
      - utils/gh-actions/schemas-action-generator.sh
  pull_request:
    paths:
      - 'schemas/alternative_investment_funds/**'
      - utils/gh-actions/schemas-action-generator.sh

jobs:
  lint-alternative_investment_funds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: korelstar/xmllint-problem-matcher@v1
    - name: Lint Schema & XML
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./schemas/alternative_investment_funds/AIF.xml
        xml-schema-file: ./schemas/alternative_investment_funds/aif.xsd
